# Generated by Django 4.0.1 on 2022-01-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='views',
        ),
        migrations.AddField(
            model_name='contents',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
