# Generated by Django 4.0.1 on 2022-02-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='games',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='match',
            name='sets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
