# Generated by Django 4.0.1 on 2022-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
