# Generated by Django 4.0.1 on 2022-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_team1_score_match_team2_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_double',
            field=models.CharField(default='복식', max_length=10),
        ),
    ]
