# Generated by Django 4.0.1 on 2022-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_is_double'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='신청', max_length=10),
        ),
    ]
